### ISSUE TITLE
Cannot find module cjs-wrapper.cjs

### ISSUE THREAD

**Issue by gilest** [rwjblue/release-it-lerna-changelog#161]
After upgrading to v4 running the `release-it` command results in the following error:

```
ERROR Cannot find module <project dir>/node_modules/release-it-lerna-changelog/cjs-wrapper.cjs'
```
